server:
  port: 8081
  ssl:
    key-store: ----
    key-store-password: ----
    key-store-type: ----
    key-alias: ----
    key-password: ----

management:
  endpoints:
    web:
      base-path: /
  server:
    port: 9000