server:
  port: 8080

  #ssl configuration
#    key-store: ${KEY_STORE}
#    key-store-password: ${KEY_STORE_PASS}
#    key-store-type: ${KEY_STORE_TYPE}
#    key-alias: ${KEY_ALIAS}
#    key-password: ${KEY_PASSWORD}

# actuator configuration
management:
  endpoint:
    health:
      show-details: always
  health:
    mongo:
      enabled: true
  endpoints:
    web:
      base-path: /

#db connection
spring:
  data:
    mongodb:
      uri: ${MONGODB_CONNECTION_STRING}